import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const { mutate: subscribeEmailMutation } = api.post.subscribeEmail.useMutation();
  
  const handleSubscribeEmail = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = e.target as HTMLFormElement;
    const formData = new FormData(form);
    const email = formData.get("email") as string;
    
    try {
      await subscribeEmailMutation({ email });
      form.reset(); // Clear the form
    } catch (error) {
      console.error("Failed to subscribe:", error);
    }
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-4xl font-bold text-white">Vercel Mailer</h1>
         <form onSubmit={handleSubscribeEmail} className="flex flex-col gap-4">
            <input 
              type="email" 
              name="email" 
              className="rounded-lg px-4 py-2 text-black"
              placeholder="Enter your email"
              aria-label="Email address"
              required
            />
            <button 
              type="submit"
              className="rounded-lg bg-white px-4 py-2 font-semibold text-black hover:bg-opacity-90 transition-colors"
            >
              Send
            </button>
          </form>
        </div>
      </main>
    </>
  );
}
